import type { ColumnMeta, GraphEdge, GraphResponse, TableNodeData } from './types.ts'

function columnLine(col: ColumnMeta): string {
  const flags = [col.is_pk && 'PK', col.is_fk && 'FK'].filter(Boolean).join(', ')
  const flagPart = flags ? ` _(${flags})_` : ''
  const commentPart = col.comment ? ` -- ${col.comment}` : ''
  const tagsPart = col.tags.length > 0 ? ` \`[${col.tags.map((t) => t.name).join(', ')}]\`` : ''
  return `| \`${col.name}\` | ${col.type} |${flagPart}${tagsPart}${commentPart} |`
}

function edgeLine(e: GraphEdge): string {
  const cols = `${e.fk_columns.join(', ')} → ${e.pk_columns.join(', ')}`
  if (e.inferred) {
    return `- ⚠️ **${e.source}** → **${e.target}** (\`${cols}\`) -- _inferred, not a declared constraint_`
  }
  const constraintPart = e.constraint_name ? ` -- \`${e.constraint_name}\`` : ''
  // † marks FKs whose target table is in a different catalog/schema than this export's
  // scope (see the footnote at the end of the Relationships section).
  const crossNote = e.cross_scope ? ' †' : ''
  return `- **${e.source}** → **${e.target}** (\`${cols}\`)${constraintPart}${crossNote}`
}

/**
 * A standalone Markdown schema doc for `graph` as given -- callers pass it through
 * scopeGraph() first if a click-to-filter selection should narrow the export. Table
 * data only -- `graph.nodes` must be TableNodeData, not the collapsed SchemaNodeData
 * shape (callers should disable this in schema_summary view).
 */
export function graphToMarkdown(graph: GraphResponse): string {
  const nodes = graph.nodes as TableNodeData[]
  const declaredEdges = graph.edges.filter((e) => !e.inferred)
  const inferredEdges = graph.edges.filter((e) => e.inferred)
  const scopeLabel = graph.unscoped ? 'all catalogs visible to this deployment' : graph.catalogs.join(', ')

  const lines: string[] = []
  lines.push(`# Schema documentation`)
  lines.push('')
  lines.push(`Generated by Catalog ERD Explorer. Scope: ${scopeLabel}.`)
  lines.push('')
  lines.push(`## Tables (${nodes.length})`)
  lines.push('')

  for (const node of nodes) {
    lines.push(`### ${node.catalog}.${node.schema}.${node.table}`)
    lines.push('')
    if (node.comment) lines.push(`> ${node.comment}`)
    if (node.tags.length > 0) {
      lines.push(`Tags: ${node.tags.map((t) => `\`${t.name}${t.value !== 'true' ? `:${t.value}` : ''}\``).join(', ')}`)
    }
    lines.push('')
    lines.push('| Column | Type | Notes |')
    lines.push('|---|---|---|')
    for (const col of node.columns) lines.push(columnLine(col))
    lines.push('')
  }

  lines.push(`## Relationships (${declaredEdges.length})`)
  lines.push('')
  if (declaredEdges.length === 0) {
    lines.push('_No declared foreign keys in this scope._')
  } else {
    for (const e of declaredEdges) lines.push(edgeLine(e))
    if (declaredEdges.some((e) => e.cross_scope)) {
      lines.push('')
      lines.push('_† Target table is in a different catalog/schema than this export\'s scope and has no entry in the Tables section above._')
    }
  }
  lines.push('')

  if (inferredEdges.length > 0) {
    lines.push(`## Inferred (undeclared) relationships (${inferredEdges.length})`)
    lines.push('')
    lines.push('_Heuristic guesses based on column name/type matching -- not real constraints._')
    lines.push('')
    for (const e of inferredEdges) lines.push(edgeLine(e))
    lines.push('')
  }

  return lines.join('\n')
}

/** The structured data model shared by the JSON and YAML exports -- a machine-readable
 * equivalent of the Markdown doc above (same fields, no prose). */
export interface ExportData {
  scope: string
  tables: Array<{
    catalog: string
    schema: string
    table: string
    comment: string | null
    tags: Array<{ name: string; value: string }>
    columns: Array<{
      name: string
      type: string
      is_primary_key: boolean
      is_foreign_key: boolean
      comment: string | null
      tags: Array<{ name: string; value: string }>
    }>
  }>
  relationships: Array<{
    source: string
    target: string
    fk_columns: string[]
    pk_columns: string[]
    constraint_name: string | null
    inferred: boolean
    // Present and true when the FK target is in a different catalog/schema than the
    // export scope -- the target has no corresponding entry in the `tables` array.
    cross_scope?: boolean
  }>
}

export function graphToExportData(graph: GraphResponse): ExportData {
  const nodes = graph.nodes as TableNodeData[]
  return {
    scope: graph.unscoped ? 'all catalogs visible to this deployment' : graph.catalogs.join(', '),
    tables: nodes.map((node) => ({
      catalog: node.catalog,
      schema: node.schema,
      table: node.table,
      comment: node.comment,
      tags: node.tags,
      columns: node.columns.map((col) => ({
        name: col.name,
        type: col.type,
        is_primary_key: col.is_pk,
        is_foreign_key: col.is_fk,
        comment: col.comment,
        tags: col.tags,
      })),
    })),
    relationships: graph.edges.map((e) => ({
      source: e.source,
      target: e.target,
      fk_columns: e.fk_columns,
      pk_columns: e.pk_columns,
      constraint_name: e.constraint_name,
      inferred: e.inferred,
      // Only included when true -- cross-catalog FKs whose target has no entry in `tables`.
      ...(e.cross_scope ? { cross_scope: true } : {}),
    })),
  }
}
