import { toPng, toSvg } from 'html-to-image'
import { getNodesBounds, getViewportForBounds, type Node } from 'reactflow'
import type { ColumnMeta, GraphEdge, GraphResponse, TableNodeData } from './types'

function download(href: string, filename: string) {
  const link = document.createElement('a')
  link.download = filename
  link.href = href
  link.click()
}

/**
 * Export exactly what's currently rendered on the canvas -- including whatever
 * dim/highlight styling click-to-filter has applied -- fit to the bounds of the
 * visible nodes, not the whole graph re-framed. Uses the documented React Flow +
 * html-to-image pattern: temporarily transform `.react-flow__viewport` to fit all
 * nodes into a fixed-size image, capture it, then let React Flow's own render take
 * back over on the next frame (no lasting DOM/style mutation).
 */
export async function exportGraphAsImage(
  nodes: Node[],
  format: 'png' | 'svg',
  filenameBase: string,
): Promise<void> {
  const viewportEl = document.querySelector('.react-flow__viewport') as HTMLElement | null
  if (!viewportEl || nodes.length === 0) return

  const bounds = getNodesBounds(nodes)
  const imageWidth = Math.max(bounds.width + 160, 800)
  const imageHeight = Math.max(bounds.height + 160, 600)
  const { x, y, zoom } = getViewportForBounds(bounds, imageWidth, imageHeight, 0.1, 2, 0.1)

  const options = {
    backgroundColor: '#f6f7f9',
    width: imageWidth,
    height: imageHeight,
    style: {
      width: `${imageWidth}px`,
      height: `${imageHeight}px`,
      transform: `translate(${x}px, ${y}px) scale(${zoom})`,
    },
  }

  const dataUrl = format === 'png' ? await toPng(viewportEl, options) : await toSvg(viewportEl, options)
  download(dataUrl, `${filenameBase}.${format}`)
}

function columnLine(col: ColumnMeta): string {
  const flags = [col.is_pk && 'PK', col.is_fk && 'FK'].filter(Boolean).join(', ')
  const flagPart = flags ? ` _(${flags})_` : ''
  const commentPart = col.comment ? ` -- ${col.comment}` : ''
  const tagsPart = col.tags.length > 0 ? ` \`[${col.tags.map((t) => t.name).join(', ')}]\`` : ''
  return `| \`${col.name}\` | ${col.type} |${flagPart}${tagsPart}${commentPart} |`
}

function edgeLine(e: GraphEdge): string {
  const cols = `${e.fk_columns.join(', ')} → ${e.pk_columns.join(', ')}`
  return e.inferred
    ? `- ⚠️ **${e.source}** → **${e.target}** (\`${cols}\`) -- _inferred, not a declared constraint_`
    : `- **${e.source}** → **${e.target}** (\`${cols}\`)${e.constraint_name ? ` -- \`${e.constraint_name}\`` : ''}`
}

/**
 * A standalone Markdown schema doc for the currently-loaded graph (i.e. whatever the
 * catalog/schema picker has selected -- not further narrowed by an ephemeral
 * click-to-filter highlight, since this is meant to document a dataset, not a moment of
 * exploration). Table data only -- `graph.nodes` must be TableNodeData, not the
 * collapsed SchemaNodeData shape (callers should disable this in schema_summary view).
 */
export function graphToMarkdown(graph: GraphResponse): string {
  const nodes = graph.nodes as TableNodeData[]
  const declaredEdges = graph.edges.filter((e) => !e.inferred)
  const inferredEdges = graph.edges.filter((e) => e.inferred)
  const scopeLabel = graph.unscoped ? 'all catalogs visible to this deployment' : graph.catalogs.join(', ')

  const lines: string[] = []
  lines.push(`# Schema documentation`)
  lines.push('')
  lines.push(`Generated by Catalog ERD Explorer. Scope: ${scopeLabel}.`)
  lines.push('')
  lines.push(`## Tables (${nodes.length})`)
  lines.push('')

  for (const node of nodes) {
    lines.push(`### ${node.catalog}.${node.schema}.${node.table}`)
    lines.push('')
    if (node.comment) lines.push(`> ${node.comment}`)
    if (node.tags.length > 0) {
      lines.push(`Tags: ${node.tags.map((t) => `\`${t.name}${t.value !== 'true' ? `:${t.value}` : ''}\``).join(', ')}`)
    }
    lines.push('')
    lines.push('| Column | Type | Notes |')
    lines.push('|---|---|---|')
    for (const col of node.columns) lines.push(columnLine(col))
    lines.push('')
  }

  lines.push(`## Relationships (${declaredEdges.length})`)
  lines.push('')
  if (declaredEdges.length === 0) {
    lines.push('_No declared foreign keys in this scope._')
  } else {
    for (const e of declaredEdges) lines.push(edgeLine(e))
  }
  lines.push('')

  if (inferredEdges.length > 0) {
    lines.push(`## Inferred (undeclared) relationships (${inferredEdges.length})`)
    lines.push('')
    lines.push('_Heuristic guesses based on column name/type matching -- not real constraints._')
    lines.push('')
    for (const e of inferredEdges) lines.push(edgeLine(e))
    lines.push('')
  }

  return lines.join('\n')
}

export function exportGraphAsMarkdown(graph: GraphResponse, filenameBase: string): void {
  const blob = new Blob([graphToMarkdown(graph)], { type: 'text/markdown' })
  download(URL.createObjectURL(blob), `${filenameBase}.md`)
}
