-- Physical model generated by Catalog ERD Explorer (dialect: sqlserver).
-- Scope: logistics, megacorp.

-- Source: logistics.shipping.carriers -- Shipping carrier master.
CREATE TABLE [logistics__shipping].[carriers] (
  [carrier_id] BIGINT NOT NULL,
  [carrier_name] NVARCHAR(MAX),
  -- One of: FREIGHT, PARCEL, OCEAN, RAIL
  [carrier_type] NVARCHAR(MAX),
  [country] NVARCHAR(MAX),
  CONSTRAINT [carriers_pk] PRIMARY KEY ([carrier_id])
);

-- Source: logistics.shipping.shipment_items -- Per-line shipment quantities, cross-linked to megacorp.erp.sales_order_lines.
CREATE TABLE [logistics__shipping].[shipment_items] (
  [shipment_item_id] BIGINT NOT NULL,
  [shipment_id] BIGINT,
  [sales_order_line_id] BIGINT,
  [quantity_shipped] BIGINT,
  CONSTRAINT [shipment_items_pk] PRIMARY KEY ([shipment_item_id])
);

-- Source: logistics.shipping.shipments -- Shipment tracking for a sales order, cross-linked to megacorp.erp.sales_orders.
CREATE TABLE [logistics__shipping].[shipments] (
  [shipment_id] BIGINT NOT NULL,
  [sales_order_id] BIGINT,
  [carrier_id] BIGINT,
  [warehouse_id] BIGINT,
  [ship_date] DATE,
  [delivery_date] DATE,
  [status] NVARCHAR(MAX),
  [tracking_number] NVARCHAR(MAX),
  CONSTRAINT [shipments_pk] PRIMARY KEY ([shipment_id])
);

-- Source: logistics.shipping.warehouses -- Distribution warehouses that fulfill sales orders.
CREATE TABLE [logistics__shipping].[warehouses] (
  [warehouse_id] BIGINT NOT NULL,
  [warehouse_name] NVARCHAR(MAX),
  [country] NVARCHAR(MAX),
  CONSTRAINT [warehouses_pk] PRIMARY KEY ([warehouse_id])
);

-- Source: megacorp.erp.cost_centers -- Finance cost centers, each tied to a factory plant.
CREATE TABLE [megacorp__erp].[cost_centers] (
  [cost_center_id] BIGINT NOT NULL,
  [cost_center_name] NVARCHAR(MAX),
  [plant_id] BIGINT,
  CONSTRAINT [cost_centers_pk] PRIMARY KEY ([cost_center_id])
);

-- Source: megacorp.erp.customers -- ERP customer master.
CREATE TABLE [megacorp__erp].[customers] (
  [customer_id] BIGINT NOT NULL,
  -- Customer legal/display name.
  [customer_name] NVARCHAR(MAX),
  [industry] NVARCHAR(MAX),
  [country] NVARCHAR(MAX),
  -- Maximum outstanding balance approved for this customer, in USD.
  [credit_limit] DECIMAL(14,2),
  [created_at] DATE,
  CONSTRAINT [customers_pk] PRIMARY KEY ([customer_id])
);

-- Source: megacorp.erp.general_ledger -- General ledger postings, optionally referencing the invoice that generated them.
CREATE TABLE [megacorp__erp].[general_ledger] (
  [gl_entry_id] BIGINT NOT NULL,
  [cost_center_id] BIGINT,
  [reference_invoice_id] BIGINT,
  [account_code] NVARCHAR(MAX),
  [debit_amount] DECIMAL(14,2),
  [credit_amount] DECIMAL(14,2),
  [posting_date] DATE,
  CONSTRAINT [general_ledger_pk] PRIMARY KEY ([gl_entry_id])
);

-- Source: megacorp.erp.invoice_line_items -- Line-item detail of an invoice.
CREATE TABLE [megacorp__erp].[invoice_line_items] (
  [invoice_line_item_id] BIGINT NOT NULL,
  [invoice_id] BIGINT,
  [description] NVARCHAR(MAX),
  [amount] DECIMAL(12,2),
  [tax_amount] DECIMAL(12,2),
  CONSTRAINT [invoice_line_items_pk] PRIMARY KEY ([invoice_line_item_id])
);

-- Source: megacorp.erp.invoices -- Customer invoices billed against a sales order.
CREATE TABLE [megacorp__erp].[invoices] (
  [invoice_id] BIGINT NOT NULL,
  [sales_order_id] BIGINT,
  [customer_id] BIGINT,
  [invoice_date] DATE,
  [due_date] DATE,
  [amount] DECIMAL(14,2),
  [status] NVARCHAR(MAX),
  CONSTRAINT [invoices_pk] PRIMARY KEY ([invoice_id])
);

-- Source: megacorp.erp.payments -- Customer payments applied against an invoice.
CREATE TABLE [megacorp__erp].[payments] (
  [payment_id] BIGINT NOT NULL,
  [invoice_id] BIGINT,
  [payment_date] DATE,
  [amount] DECIMAL(14,2),
  [payment_method] NVARCHAR(MAX),
  CONSTRAINT [payments_pk] PRIMARY KEY ([payment_id])
);

-- Source: megacorp.erp.purchase_order_lines -- Line items of a purchase order, referencing the raw-material/component being procured.
CREATE TABLE [megacorp__erp].[purchase_order_lines] (
  [purchase_order_line_id] BIGINT NOT NULL,
  [purchase_order_id] BIGINT,
  [material_id] BIGINT,
  [quantity] BIGINT,
  [unit_cost] DECIMAL(12,2),
  CONSTRAINT [purchase_order_lines_pk] PRIMARY KEY ([purchase_order_line_id])
);

-- Source: megacorp.erp.purchase_orders -- Purchase orders issued to vendors.
CREATE TABLE [megacorp__erp].[purchase_orders] (
  [purchase_order_id] BIGINT NOT NULL,
  [vendor_id] BIGINT,
  [order_date] DATE,
  [status] NVARCHAR(MAX),
  [total_amount] DECIMAL(14,2),
  CONSTRAINT [purchase_orders_pk] PRIMARY KEY ([purchase_order_id])
);

-- Source: megacorp.erp.sales_order_lines -- Line items of a sales order, referencing the finished-goods material sold.
CREATE TABLE [megacorp__erp].[sales_order_lines] (
  [sales_order_line_id] BIGINT NOT NULL,
  [sales_order_id] BIGINT,
  [material_id] BIGINT,
  [quantity] BIGINT,
  [unit_price] DECIMAL(12,2),
  CONSTRAINT [sales_order_lines_pk] PRIMARY KEY ([sales_order_line_id])
);

-- Source: megacorp.erp.sales_orders -- Customer sales orders.
CREATE TABLE [megacorp__erp].[sales_orders] (
  [sales_order_id] BIGINT NOT NULL,
  [customer_id] BIGINT,
  [order_date] DATE,
  [status] NVARCHAR(MAX),
  [total_amount] DECIMAL(14,2),
  CONSTRAINT [sales_orders_pk] PRIMARY KEY ([sales_order_id])
);

-- Source: megacorp.erp.vendors -- ERP vendor/supplier master.
CREATE TABLE [megacorp__erp].[vendors] (
  [vendor_id] BIGINT NOT NULL,
  -- Vendor legal/display name.
  [vendor_name] NVARCHAR(MAX),
  [country] NVARCHAR(MAX),
  [payment_terms] NVARCHAR(MAX),
  CONSTRAINT [vendors_pk] PRIMARY KEY ([vendor_id])
);

-- Source: megacorp.factory.bill_of_materials -- Bill of materials: which component materials make up a parent (finished good) material.
CREATE TABLE [megacorp__factory].[bill_of_materials] (
  [bom_id] BIGINT NOT NULL,
  [parent_material_id] BIGINT,
  [component_material_id] BIGINT,
  [quantity_required] DECIMAL(12,4),
  CONSTRAINT [bill_of_materials_pk] PRIMARY KEY ([bom_id])
);

-- Source: megacorp.factory.machine_sensor_readings -- IoT sensor telemetry from factory machines.
CREATE TABLE [megacorp__factory].[machine_sensor_readings] (
  [reading_id] BIGINT NOT NULL,
  [machine_id] BIGINT,
  [reading_timestamp] DATETIME2,
  [temperature_c] FLOAT,
  [vibration_mm_s] FLOAT,
  [pressure_bar] FLOAT,
  CONSTRAINT [machine_sensor_readings_pk] PRIMARY KEY ([reading_id])
);

-- Source: megacorp.factory.machines -- Machines assigned to a production line.
CREATE TABLE [megacorp__factory].[machines] (
  [machine_id] BIGINT NOT NULL,
  [production_line_id] BIGINT,
  [machine_type] NVARCHAR(MAX),
  [install_date] DATE,
  [status] NVARCHAR(MAX),
  CONSTRAINT [machines_pk] PRIMARY KEY ([machine_id])
);

-- Source: megacorp.factory.materials -- Materials master: raw materials, components, and finished goods.
CREATE TABLE [megacorp__factory].[materials] (
  [material_id] BIGINT NOT NULL,
  [material_name] NVARCHAR(MAX),
  -- RAW_MATERIAL, COMPONENT, or FINISHED_GOOD
  [material_type] NVARCHAR(MAX),
  [unit_of_measure] NVARCHAR(MAX),
  [standard_cost] DECIMAL(12,2),
  CONSTRAINT [materials_pk] PRIMARY KEY ([material_id])
);

-- Source: megacorp.factory.operators -- Factory-floor operators assigned to a plant.
CREATE TABLE [megacorp__factory].[operators] (
  [operator_id] BIGINT NOT NULL,
  [plant_id] BIGINT,
  -- Operator full name.
  [operator_name] NVARCHAR(MAX),
  [hire_date] DATE,
  [certification_level] NVARCHAR(MAX),
  CONSTRAINT [operators_pk] PRIMARY KEY ([operator_id])
);

-- Source: megacorp.factory.plants -- Physical manufacturing plants.
CREATE TABLE [megacorp__factory].[plants] (
  [plant_id] BIGINT NOT NULL,
  [plant_name] NVARCHAR(MAX),
  [location] NVARCHAR(MAX),
  [country] NVARCHAR(MAX),
  [capacity_units_per_day] BIGINT,
  CONSTRAINT [plants_pk] PRIMARY KEY ([plant_id])
);

-- Source: megacorp.factory.production_lines -- Production lines within a plant.
CREATE TABLE [megacorp__factory].[production_lines] (
  [production_line_id] BIGINT NOT NULL,
  [plant_id] BIGINT,
  [line_name] NVARCHAR(MAX),
  [line_type] NVARCHAR(MAX),
  CONSTRAINT [production_lines_pk] PRIMARY KEY ([production_line_id])
);

-- Source: megacorp.factory.quality_inspections -- Quality inspection results tied to a work order.
CREATE TABLE [megacorp__factory].[quality_inspections] (
  [inspection_id] BIGINT NOT NULL,
  [work_order_id] BIGINT,
  -- Inspector full name.
  [inspector_name] NVARCHAR(MAX),
  [inspection_date] DATE,
  [result] NVARCHAR(MAX),
  [defect_count] BIGINT,
  -- The operator believed responsible for the inspection outcome. Not a declared FK.
  [operator_id] BIGINT,
  CONSTRAINT [quality_inspections_pk] PRIMARY KEY ([inspection_id])
);

-- Source: megacorp.factory.shifts -- Shift definitions per plant.
CREATE TABLE [megacorp__factory].[shifts] (
  [shift_id] BIGINT NOT NULL,
  [plant_id] BIGINT,
  [shift_name] NVARCHAR(MAX),
  [start_time] NVARCHAR(MAX),
  [end_time] NVARCHAR(MAX),
  CONSTRAINT [shifts_pk] PRIMARY KEY ([shift_id])
);

-- Source: megacorp.factory.work_order_operators -- Junction table: which operators worked which work order during which shift (many-to-many).
CREATE TABLE [megacorp__factory].[work_order_operators] (
  [work_order_id] BIGINT NOT NULL,
  [operator_id] BIGINT NOT NULL,
  [shift_id] BIGINT NOT NULL,
  [hours_worked] DECIMAL(5,2),
  CONSTRAINT [work_order_operators_pk] PRIMARY KEY ([work_order_id], [operator_id], [shift_id])
);

-- Source: megacorp.factory.work_orders -- Production work orders for a given material on a given line.
CREATE TABLE [megacorp__factory].[work_orders] (
  [work_order_id] BIGINT NOT NULL,
  [production_line_id] BIGINT,
  [material_id] BIGINT,
  [quantity_planned] BIGINT,
  [quantity_produced] BIGINT,
  [start_date] DATE,
  [end_date] DATE,
  -- One of: PLANNED, IN_PROGRESS, COMPLETED, CANCELLED.
  [status] NVARCHAR(MAX),
  CONSTRAINT [work_orders_pk] PRIMARY KEY ([work_order_id])
);

-- Foreign keys (declared Unity Catalog constraints only -- undeclared/inferred
-- relationships are listed in metadata.csv, never as a DDL constraint here).
ALTER TABLE [megacorp__factory].[bill_of_materials] ADD CONSTRAINT [bom_component_material_id_fk] FOREIGN KEY ([component_material_id]) REFERENCES [megacorp__factory].[materials] ([material_id]);
ALTER TABLE [megacorp__factory].[bill_of_materials] ADD CONSTRAINT [bom_parent_material_id_fk] FOREIGN KEY ([parent_material_id]) REFERENCES [megacorp__factory].[materials] ([material_id]);
ALTER TABLE [megacorp__erp].[cost_centers] ADD CONSTRAINT [cost_centers_plant_id_fk] FOREIGN KEY ([plant_id]) REFERENCES [megacorp__factory].[plants] ([plant_id]);
ALTER TABLE [megacorp__erp].[general_ledger] ADD CONSTRAINT [general_ledger_cost_center_id_fk] FOREIGN KEY ([cost_center_id]) REFERENCES [megacorp__erp].[cost_centers] ([cost_center_id]);
ALTER TABLE [megacorp__erp].[general_ledger] ADD CONSTRAINT [general_ledger_reference_invoice_id_fk] FOREIGN KEY ([reference_invoice_id]) REFERENCES [megacorp__erp].[invoices] ([invoice_id]);
ALTER TABLE [megacorp__erp].[invoice_line_items] ADD CONSTRAINT [invoice_line_items_invoice_id_fk] FOREIGN KEY ([invoice_id]) REFERENCES [megacorp__erp].[invoices] ([invoice_id]);
ALTER TABLE [megacorp__erp].[invoices] ADD CONSTRAINT [invoices_customer_id_fk] FOREIGN KEY ([customer_id]) REFERENCES [megacorp__erp].[customers] ([customer_id]);
ALTER TABLE [megacorp__erp].[invoices] ADD CONSTRAINT [invoices_sales_order_id_fk] FOREIGN KEY ([sales_order_id]) REFERENCES [megacorp__erp].[sales_orders] ([sales_order_id]);
ALTER TABLE [megacorp__factory].[machine_sensor_readings] ADD CONSTRAINT [machine_sensor_readings_machine_id_fk] FOREIGN KEY ([machine_id]) REFERENCES [megacorp__factory].[machines] ([machine_id]);
ALTER TABLE [megacorp__factory].[machines] ADD CONSTRAINT [machines_production_line_id_fk] FOREIGN KEY ([production_line_id]) REFERENCES [megacorp__factory].[production_lines] ([production_line_id]);
ALTER TABLE [megacorp__factory].[operators] ADD CONSTRAINT [operators_plant_id_fk] FOREIGN KEY ([plant_id]) REFERENCES [megacorp__factory].[plants] ([plant_id]);
ALTER TABLE [megacorp__erp].[payments] ADD CONSTRAINT [payments_invoice_id_fk] FOREIGN KEY ([invoice_id]) REFERENCES [megacorp__erp].[invoices] ([invoice_id]);
ALTER TABLE [megacorp__factory].[production_lines] ADD CONSTRAINT [production_lines_plant_id_fk] FOREIGN KEY ([plant_id]) REFERENCES [megacorp__factory].[plants] ([plant_id]);
ALTER TABLE [megacorp__erp].[purchase_order_lines] ADD CONSTRAINT [purchase_order_lines_material_id_fk] FOREIGN KEY ([material_id]) REFERENCES [megacorp__factory].[materials] ([material_id]);
ALTER TABLE [megacorp__erp].[purchase_order_lines] ADD CONSTRAINT [purchase_order_lines_purchase_order_id_fk] FOREIGN KEY ([purchase_order_id]) REFERENCES [megacorp__erp].[purchase_orders] ([purchase_order_id]);
ALTER TABLE [megacorp__erp].[purchase_orders] ADD CONSTRAINT [purchase_orders_vendor_id_fk] FOREIGN KEY ([vendor_id]) REFERENCES [megacorp__erp].[vendors] ([vendor_id]);
ALTER TABLE [megacorp__factory].[quality_inspections] ADD CONSTRAINT [quality_inspections_work_order_id_fk] FOREIGN KEY ([work_order_id]) REFERENCES [megacorp__factory].[work_orders] ([work_order_id]);
ALTER TABLE [megacorp__erp].[sales_order_lines] ADD CONSTRAINT [sales_order_lines_material_id_fk] FOREIGN KEY ([material_id]) REFERENCES [megacorp__factory].[materials] ([material_id]);
ALTER TABLE [megacorp__erp].[sales_order_lines] ADD CONSTRAINT [sales_order_lines_sales_order_id_fk] FOREIGN KEY ([sales_order_id]) REFERENCES [megacorp__erp].[sales_orders] ([sales_order_id]);
ALTER TABLE [megacorp__erp].[sales_orders] ADD CONSTRAINT [sales_orders_customer_id_fk] FOREIGN KEY ([customer_id]) REFERENCES [megacorp__erp].[customers] ([customer_id]);
ALTER TABLE [megacorp__factory].[shifts] ADD CONSTRAINT [shifts_plant_id_fk] FOREIGN KEY ([plant_id]) REFERENCES [megacorp__factory].[plants] ([plant_id]);
ALTER TABLE [logistics__shipping].[shipment_items] ADD CONSTRAINT [shipment_items_sales_order_line_id_fk] FOREIGN KEY ([sales_order_line_id]) REFERENCES [megacorp__erp].[sales_order_lines] ([sales_order_line_id]);
ALTER TABLE [logistics__shipping].[shipment_items] ADD CONSTRAINT [shipment_items_shipment_id_fk] FOREIGN KEY ([shipment_id]) REFERENCES [logistics__shipping].[shipments] ([shipment_id]);
ALTER TABLE [logistics__shipping].[shipments] ADD CONSTRAINT [shipments_carrier_id_fk] FOREIGN KEY ([carrier_id]) REFERENCES [logistics__shipping].[carriers] ([carrier_id]);
ALTER TABLE [logistics__shipping].[shipments] ADD CONSTRAINT [shipments_sales_order_id_fk] FOREIGN KEY ([sales_order_id]) REFERENCES [megacorp__erp].[sales_orders] ([sales_order_id]);
ALTER TABLE [logistics__shipping].[shipments] ADD CONSTRAINT [shipments_warehouse_id_fk] FOREIGN KEY ([warehouse_id]) REFERENCES [logistics__shipping].[warehouses] ([warehouse_id]);
ALTER TABLE [megacorp__factory].[work_order_operators] ADD CONSTRAINT [wo_operators_operator_id_fk] FOREIGN KEY ([operator_id]) REFERENCES [megacorp__factory].[operators] ([operator_id]);
ALTER TABLE [megacorp__factory].[work_order_operators] ADD CONSTRAINT [wo_operators_shift_id_fk] FOREIGN KEY ([shift_id]) REFERENCES [megacorp__factory].[shifts] ([shift_id]);
ALTER TABLE [megacorp__factory].[work_order_operators] ADD CONSTRAINT [wo_operators_work_order_id_fk] FOREIGN KEY ([work_order_id]) REFERENCES [megacorp__factory].[work_orders] ([work_order_id]);
ALTER TABLE [megacorp__factory].[work_orders] ADD CONSTRAINT [work_orders_material_id_fk] FOREIGN KEY ([material_id]) REFERENCES [megacorp__factory].[materials] ([material_id]);
ALTER TABLE [megacorp__factory].[work_orders] ADD CONSTRAINT [work_orders_production_line_id_fk] FOREIGN KEY ([production_line_id]) REFERENCES [megacorp__factory].[production_lines] ([production_line_id]);
