"""
Genie Conversation Wrapper for Brand Manager Forecasting Intelligence.

Wraps the Databricks Genie API to ask natural-language questions against
pre-configured Genie Spaces and returns structured results including
the answer text, generated SQL, and a pandas DataFrame of results.
"""

import time
import logging
from typing import Optional

import pandas as pd
from databricks.sdk import WorkspaceClient

try:
    from databricks.sdk.service.dashboards import (
        GenieMessage,
        GenieGetMessageQueryResultResponse,
    )
except ImportError:
    # Older SDK versions may not expose these classes directly.
    # We only used them for type hints, so set to None and rely on duck typing.
    GenieMessage = None  # type: ignore
    GenieGetMessageQueryResultResponse = None  # type: ignore

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
GENIE_TIMEOUT_SECONDS = 120
GENIE_POLL_INTERVAL = 2.0
MAX_RETRIES = 2


def _workspace_client() -> WorkspaceClient:
    """Return a fresh WorkspaceClient (auto-authenticates in Databricks Apps)."""
    return WorkspaceClient()


def _extract_query_result_df(
    w: WorkspaceClient,
    space_id: str,
    conversation_id: str,
    message_id: str,
) -> tuple[Optional[pd.DataFrame], Optional[str]]:
    """Attempt to pull the SQL query and result DataFrame from a Genie message."""
    sql_query: Optional[str] = None
    result_df: Optional[pd.DataFrame] = None

    try:
        query_result = (
            w.genie.get_message_query_result(
                space_id=space_id,
                conversation_id=conversation_id,
                message_id=message_id,
            )
        )

        # Extract the statement / SQL
        if hasattr(query_result, "statement_response"):
            sr = query_result.statement_response
            # SQL text
            if hasattr(sr, "manifest") and sr.manifest and hasattr(sr.manifest, "sql"):
                sql_query = sr.manifest.sql

            # Build DataFrame from result data
            if hasattr(sr, "result") and sr.result and hasattr(sr.result, "data_array"):
                columns = []
                if hasattr(sr, "manifest") and sr.manifest and hasattr(sr.manifest, "schema"):
                    schema = sr.manifest.schema
                    if hasattr(schema, "columns") and schema.columns:
                        columns = [c.name for c in schema.columns]

                data = sr.result.data_array or []
                if columns and data:
                    result_df = pd.DataFrame(data, columns=columns)
                elif data:
                    result_df = pd.DataFrame(data)
    except Exception as e:
        logger.warning("Could not extract query result: %s", e)

    return result_df, sql_query


def ask_genie(space_id: str, question: str) -> dict:
    """Ask a question to a Genie Space and return structured results.

    Returns:
        dict with keys:
            - answer_text (str): The natural-language answer from Genie.
            - sql_query (str | None): The SQL generated by Genie.
            - result_df (pd.DataFrame | None): Query results as a DataFrame.
            - error (str | None): Error message if the call failed.
    """
    last_error: Optional[str] = None

    for attempt in range(1, MAX_RETRIES + 1):
        try:
            w = _workspace_client()

            # Start conversation and wait for the complete response
            message = w.genie.start_conversation_and_wait(
                space_id=space_id,
                content=question,
            )

            # Extract answer text from attachments or content
            answer_text = ""
            sql_query = None
            result_df = None

            if message.attachments:
                for att in message.attachments:
                    if hasattr(att, "text") and att.text and hasattr(att.text, "content"):
                        answer_text += att.text.content + "\n"
                    # If there is a query attachment, try to extract results
                    if hasattr(att, "query") and att.query:
                        query_att = att.query
                        if hasattr(query_att, "query") and query_att.query:
                            sql_query = query_att.query
                        if hasattr(query_att, "description") and query_att.description:
                            if not answer_text:
                                answer_text = query_att.description

            # Try to get the query result DataFrame
            if message.conversation_id and message.id:
                df, extracted_sql = _extract_query_result_df(
                    w, space_id, message.conversation_id, message.id
                )
                if df is not None:
                    result_df = df
                if extracted_sql and not sql_query:
                    sql_query = extracted_sql

            # Fallback: use message content if no answer from attachments
            if not answer_text and hasattr(message, "content") and message.content:
                answer_text = message.content

            if not answer_text:
                answer_text = "Genie returned results. See the data table below."

            return {
                "answer_text": answer_text.strip(),
                "sql_query": sql_query,
                "result_df": result_df,
                "error": None,
            }

        except Exception as e:
            last_error = str(e)
            logger.warning(
                "Genie call attempt %d/%d failed for space %s: %s",
                attempt, MAX_RETRIES, space_id, e,
            )
            if attempt < MAX_RETRIES:
                time.sleep(3)

    return {
        "answer_text": "",
        "sql_query": None,
        "result_df": None,
        "error": f"Genie API call failed after {MAX_RETRIES} attempts: {last_error}",
    }
