"""
Report & Alert Runner for Brand Manager Forecasting Intelligence.

Handles both scheduled reports and anomaly alerts:
- Reports: Always run the Supervisor Agent, generate PDF, send email.
- Alerts: Run the Supervisor Agent, ask LLM if there's an issue, only send if breached.

Can be invoked from the Streamlit app (preview/test) or as a standalone
Databricks Job task with schedule_id as a parameter.
"""

import io
import json
import logging
import os
import uuid
from datetime import datetime
from typing import Optional

import markdown

# SMTP transport lives in its own module — re-exported here for existing callers.
from email_utils import send_email, smtp_available  # noqa: F401

logger = logging.getLogger(__name__)

APP_URL = os.environ.get("APP_URL", "")


# ---------------------------------------------------------------------------
# Markdown -> HTML report
# ---------------------------------------------------------------------------
REPORT_CSS = """
body { font-family: 'Segoe UI', Arial, sans-serif; color: #1a1a1a; max-width: 800px; margin: 0 auto; padding: 24px; }
h1 { color: #cc0000; border-bottom: 2px solid #cc0000; padding-bottom: 8px; }
h2 { color: #333; margin-top: 28px; }
h3 { color: #555; }
table { border-collapse: collapse; width: 100%; margin: 16px 0; }
th { background: #cc0000; color: white; padding: 10px 12px; text-align: left; font-size: 13px; }
td { padding: 8px 12px; border-bottom: 1px solid #e0e0e0; font-size: 13px; }
tr:nth-child(even) { background: #f9f9f9; }
.exec-summary { background: #fff3cd; border-left: 4px solid #ffc107; padding: 16px; margin: 16px 0; border-radius: 4px; }
.alert-banner { background: #f8d7da; border-left: 4px solid #dc3545; padding: 16px; margin: 16px 0; border-radius: 4px; }
.footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #ddd; font-size: 12px; color: #888; }
ul, ol { padding-left: 24px; }
li { margin-bottom: 6px; }
strong { color: #1a1a1a; }
"""


def markdown_to_html(report_md: str, title: str = "Report", is_alert: bool = False) -> str:
    """Convert a markdown report to a styled HTML document.

    Vega-Lite specs are rendered to PNG and embedded as base64 <img> tags.
    """
    import base64

    # Split out charts, render to PNG, and build HTML segments
    chart_html_parts = []
    try:
        from viz_utils import split_markdown_and_charts, spec_to_png
        segments = split_markdown_and_charts(report_md)
        for seg in segments:
            if seg["type"] == "vega-lite":
                png = spec_to_png(seg["spec"])
                if png:
                    b64 = base64.b64encode(png).decode("ascii")
                    chart_html_parts.append(
                        f'<div style="text-align:center;margin:16px 0;">'
                        f'<img src="data:image/png;base64,{b64}" '
                        f'style="max-width:100%;border:1px solid #e0e0e0;border-radius:4px;" />'
                        f'</div>'
                    )
                # else: skip failed chart silently
            else:
                chart_html_parts.append(
                    markdown.markdown(seg["content"], extensions=["tables", "fenced_code"])
                )
    except ImportError:
        chart_html_parts.append(
            markdown.markdown(report_md, extensions=["tables", "fenced_code"])
        )

    html_body = "\n".join(chart_html_parts)

    banner = ""
    if is_alert:
        banner = '<div class="alert-banner"><strong>ALERT TRIGGERED</strong> — This alert fired because the Supervisor Agent identified an actionable issue.</div>'

    timestamp = datetime.utcnow().strftime("%B %d, %Y at %H:%M UTC")
    app_link = f'<a href="{APP_URL}">Open in App</a>' if APP_URL else ""

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>{title}</title><style>{REPORT_CSS}</style></head>
<body>
<h1>{title}</h1>
{banner}
{html_body}
<div class="footer">
    Generated by Brand Manager Forecasting Intelligence on {timestamp}. {app_link}
</div>
</body>
</html>"""


# ---------------------------------------------------------------------------
# PDF generation — direct markdown rendering for clean layout
# ---------------------------------------------------------------------------
# Brand accent color
_AD_RED = (204, 0, 0)
_DARK = (30, 30, 30)
_GRAY = (100, 100, 100)
_LIGHT_BG = (245, 245, 245)
_HIGHLIGHT_BG = (255, 243, 205)


def _init_pdf_fonts(pdf):
    """Register DejaVu Unicode fonts bundled in app/fonts/."""
    from pathlib import Path
    font_dir = Path(__file__).parent / "fonts"
    pdf.add_font("DejaVu", "", str(font_dir / "DejaVuSans.ttf"))
    pdf.add_font("DejaVu", "B", str(font_dir / "DejaVuSans-Bold.ttf"))
    pdf.add_font("DejaVu", "I", str(font_dir / "DejaVuSans-Oblique.ttf"))
    pdf.add_font("DejaVu", "BI", str(font_dir / "DejaVuSans-BoldOblique.ttf"))


def _render_inline(pdf, text: str, default_style: str = ""):
    """Render a line of text with **bold** and *italic* inline spans."""
    import re
    # Split on bold and italic markers
    parts = re.split(r'(\*\*.*?\*\*|\*.*?\*)', text)
    for part in parts:
        if part.startswith("**") and part.endswith("**"):
            pdf.set_font("DejaVu", "B", pdf.font_size_pt)
            pdf.write(5, part[2:-2])
            pdf.set_font("DejaVu", default_style, pdf.font_size_pt)
        elif part.startswith("*") and part.endswith("*"):
            pdf.set_font("DejaVu", "I", pdf.font_size_pt)
            pdf.write(5, part[1:-1])
            pdf.set_font("DejaVu", default_style, pdf.font_size_pt)
        else:
            pdf.write(5, part)


def _render_text_segment(pdf, text: str, left_margin: float):
    """Render a block of markdown text (no Vega-Lite) into the PDF."""
    lines = text.split("\n")
    in_list = False
    numbered_idx = 0

    for line in lines:
        stripped = line.strip()

        if not stripped:
            if in_list:
                in_list = False
                numbered_idx = 0
            pdf.ln(3)
            continue

        # H1
        if stripped.startswith("# ") and not stripped.startswith("##"):
            pdf.ln(4)
            pdf.set_font("DejaVu", "B", 18)
            pdf.set_text_color(*_AD_RED)
            pdf.cell(0, 10, stripped[2:], new_x="LMARGIN", new_y="NEXT")
            pdf.set_draw_color(*_AD_RED)
            pdf.line(left_margin, pdf.get_y(), 190, pdf.get_y())
            pdf.ln(3)
            pdf.set_text_color(*_DARK)
            continue

        # H2
        if stripped.startswith("## ") and not stripped.startswith("###"):
            pdf.ln(6)
            pdf.set_font("DejaVu", "B", 14)
            pdf.set_text_color(*_AD_RED)
            pdf.cell(0, 8, stripped[3:], new_x="LMARGIN", new_y="NEXT")
            pdf.set_draw_color(200, 200, 200)
            pdf.line(left_margin, pdf.get_y() + 1, 190, pdf.get_y() + 1)
            pdf.ln(4)
            pdf.set_text_color(*_DARK)
            continue

        # H3
        if stripped.startswith("### "):
            pdf.ln(4)
            pdf.set_font("DejaVu", "B", 12)
            pdf.set_text_color(60, 60, 60)
            pdf.cell(0, 7, stripped[4:], new_x="LMARGIN", new_y="NEXT")
            pdf.ln(2)
            pdf.set_text_color(*_DARK)
            continue

        # Horizontal rule
        if stripped in ("---", "***", "___"):
            pdf.ln(3)
            pdf.set_draw_color(200, 200, 200)
            pdf.line(left_margin, pdf.get_y(), 190, pdf.get_y())
            pdf.ln(3)
            continue

        # Bullet list
        if stripped.startswith("- ") or stripped.startswith("* ") or stripped.startswith("\u2022 "):
            in_list = True
            bullet_text = stripped.lstrip("-*\u2022 ").strip()
            pdf.set_font("DejaVu", "", 10)
            pdf.cell(6, 5, "\u2022")
            _render_inline(pdf, bullet_text)
            pdf.ln(6)
            continue

        # Numbered list
        if len(stripped) > 2 and stripped[0].isdigit() and stripped[1] in (".", ")"):
            in_list = True
            numbered_idx += 1
            item_text = stripped[2:].strip().lstrip(". )")
            pdf.set_font("DejaVu", "B", 10)
            pdf.cell(8, 5, f"{numbered_idx}.")
            pdf.set_font("DejaVu", "", 10)
            _render_inline(pdf, item_text)
            pdf.ln(6)
            continue

        if len(stripped) > 3 and stripped[:2].isdigit() and stripped[2] in (".", ")"):
            in_list = True
            numbered_idx += 1
            item_text = stripped[3:].strip().lstrip(". )")
            pdf.set_font("DejaVu", "B", 10)
            pdf.cell(8, 5, f"{numbered_idx}.")
            pdf.set_font("DejaVu", "", 10)
            _render_inline(pdf, item_text)
            pdf.ln(6)
            continue

        # Regular paragraph text
        pdf.set_font("DejaVu", "", 10)
        _render_inline(pdf, stripped)
        pdf.ln(5)


def html_to_pdf(html_content: str, report_md: str = "", title: str = "") -> Optional[bytes]:
    """Build a branded PDF directly from markdown for clean formatting.

    Falls back to the HTML content if report_md is not provided.
    """
    try:
        from fpdf import FPDF

        pdf = FPDF(orientation="P", unit="mm", format="A4")
        pdf.set_auto_page_break(auto=True, margin=25)
        _init_pdf_fonts(pdf)

        # -- Title page header --
        pdf.add_page()
        left_margin = 20
        pdf.set_left_margin(left_margin)
        pdf.set_right_margin(20)

        # Red header bar
        pdf.set_fill_color(*_AD_RED)
        pdf.rect(0, 0, 210, 28, "F")
        pdf.set_font("DejaVu", "B", 18)
        pdf.set_text_color(255, 255, 255)
        pdf.set_xy(left_margin, 6)
        display_title = title
        # Extract title from HTML if not provided
        if not display_title and "<h1>" in html_content:
            display_title = html_content.split("<h1>")[1].split("</h1>")[0]
        if not display_title:
            display_title = "Report"
        pdf.cell(0, 10, display_title, new_x="LMARGIN", new_y="NEXT")

        # Subtitle line
        pdf.set_font("DejaVu", "I", 9)
        pdf.set_text_color(220, 220, 220)
        timestamp = datetime.utcnow().strftime("%B %d, %Y at %H:%M UTC")
        pdf.cell(0, 5, f"Generated {timestamp}", new_x="LMARGIN", new_y="NEXT")

        pdf.set_text_color(*_DARK)
        pdf.ln(12)

        # -- Parse markdown if available, otherwise fall back to HTML body text --
        if not report_md:
            # Extract text from HTML as fallback
            import re
            text = html_content
            if "<body>" in text:
                text = text.split("<body>", 1)[1].rsplit("</body>", 1)[0]
            text = re.sub(r'<[^>]+>', '', text)
            pdf.set_font("DejaVu", "", 10)
            pdf.multi_cell(0, 5, text)
            return bytes(pdf.output())

        # -- Pre-render Vega-Lite charts and strip them from markdown --
        _spec_to_png = None
        try:
            from viz_utils import split_markdown_and_charts, spec_to_png as _s2p
            segments = split_markdown_and_charts(report_md)
            _spec_to_png = _s2p
        except ImportError:
            segments = [{"type": "text", "content": report_md}]

        # Render each segment: text segments go through the line-by-line
        # renderer, chart segments get rendered as PNG images.
        for segment in segments:
            if segment["type"] == "vega-lite":
                png = _spec_to_png(segment["spec"]) if _spec_to_png else None
                if png:
                    try:
                        pdf.ln(4)
                        img_data = io.BytesIO(png)
                        pdf.image(img_data, x=left_margin, w=170)
                        pdf.ln(4)
                    except Exception as img_err:
                        logger.warning("Failed to embed chart image in PDF: %s", img_err)
                continue

            # -- Render text segment line by line --
            _render_text_segment(pdf, segment["content"], left_margin)

        # -- Footer --
        pdf.ln(10)
        pdf.set_draw_color(200, 200, 200)
        pdf.line(left_margin, pdf.get_y(), 190, pdf.get_y())
        pdf.ln(3)
        pdf.set_font("DejaVu", "I", 8)
        pdf.set_text_color(*_GRAY)
        pdf.cell(0, 4, f"Generated by Brand Manager Forecasting Intelligence on {timestamp}",
                 new_x="LMARGIN", new_y="NEXT")
        if APP_URL:
            pdf.set_text_color(0, 102, 204)
            pdf.cell(0, 4, "Open in App", link=APP_URL)

        return bytes(pdf.output())
    except ImportError:
        logger.warning("fpdf2 not installed -- PDF generation skipped.")
        return None
    except Exception as e:
        logger.error("PDF generation failed: %s", e)
        return None


# ---------------------------------------------------------------------------
# File naming
# ---------------------------------------------------------------------------
def make_pdf_filename(title: str, timestamp: Optional[datetime] = None) -> str:
    """Generate a snake_case PDF filename from a report title + timestamp.

    e.g. "Weekly Accuracy Report" -> "weekly_accuracy_report_20260307_0454.pdf"
    """
    import re
    ts = timestamp or datetime.utcnow()
    # Lowercase, replace non-alphanumeric with underscore, collapse multiple underscores
    slug = re.sub(r'[^a-z0-9]+', '_', title.lower()).strip('_')
    return f"{slug}_{ts.strftime('%Y%m%d_%H%M')}.pdf"


# ---------------------------------------------------------------------------
# UC Volume storage
# ---------------------------------------------------------------------------
def save_to_volume(
    pdf_bytes: bytes,
    title: str,
    workspace_client=None,
) -> Optional[str]:
    """Save PDF to UC Volume. Returns the volume path or None."""
    try:
        if workspace_client is None:
            from databricks.sdk import WorkspaceClient
            workspace_client = WorkspaceClient()

        filename = make_pdf_filename(title)
        volume_path = f"/Volumes/brand_intel_demo/assets/reports/{filename}"

        workspace_client.files.upload(
            volume_path,
            io.BytesIO(pdf_bytes),
            overwrite=True,
        )
        logger.info("PDF saved to %s", volume_path)
        return volume_path
    except Exception as e:
        logger.error("Failed to save PDF to UC Volume: %s", e)
        return None


# ---------------------------------------------------------------------------
# Main runner
# ---------------------------------------------------------------------------
def run_schedule(schedule_id: str, workspace_client=None) -> dict:
    """Execute a scheduled report or alert by schedule_id.

    Reads config from Lakebase, runs the Supervisor Agent, and handles
    email delivery + PDF storage.

    Returns dict with: status, report, alert_breached, run_id, email_sent.
    """
    from supervisor import SupervisorAgent
    from db import execute_query, execute_insert

    # 1. Read schedule config
    schedule_df = execute_query(
        """
        SELECT schedule_id, schedule_type, report_name, report_question,
               alert_template, alert_threshold, alert_scope_json,
               alert_cooldown_days, last_alert_sent_at,
               recipients, created_by, genie_space_ids
        FROM bi_report_schedules
        WHERE schedule_id = %s AND is_active = TRUE
        """,
        (schedule_id,),
    )

    if schedule_df.empty:
        return {"status": "error", "error": "Schedule not found or inactive"}

    config = schedule_df.iloc[0]
    schedule_type = config.get("schedule_type", "report")
    report_name = config.get("report_name", "Untitled")
    question = config.get("report_question", "")
    recipients = config.get("recipients", [])
    created_by = config.get("created_by", "unknown@example.com")
    run_id = str(uuid.uuid4())

    if isinstance(recipients, str):
        recipients = [r.strip() for r in recipients.split(",") if r.strip()]
    if not recipients:
        recipients = [created_by]

    # 2. For alerts: check cooldown
    if schedule_type == "alert":
        cooldown_days = config.get("alert_cooldown_days") or 1
        last_sent = config.get("last_alert_sent_at")
        if last_sent:
            from datetime import timedelta
            if datetime.utcnow() - last_sent < timedelta(days=cooldown_days):
                logger.info("Alert %s is in cooldown — skipping", schedule_id)
                execute_insert(
                    """
                    INSERT INTO bi_report_audit_log
                        (run_id, schedule_id, run_started_at, run_completed_at, status,
                         alert_breached)
                    VALUES (%s, %s, now(), now(), 'cooldown', FALSE)
                    """,
                    (run_id, schedule_id),
                )
                return {"status": "cooldown", "run_id": run_id}

    # 3. Run Supervisor Agent — resolve genie spaces for this schedule
    from db import get_genies_by_ids, get_active_genies as _get_active_genies
    genie_space_ids = config.get("genie_space_ids")
    if genie_space_ids:
        genies_df = get_genies_by_ids(genie_space_ids)
    else:
        genies_df = _get_active_genies()
    genies = genies_df.to_dict("records")
    agent = SupervisorAgent(workspace_client=workspace_client, genies=genies)
    try:
        result = agent.run(
            question=question,
            user_email=created_by,
        )
    except Exception as e:
        logger.error("Agent run failed for schedule %s: %s", schedule_id, e)
        execute_insert(
            """
            INSERT INTO bi_report_audit_log
                (run_id, schedule_id, run_started_at, run_completed_at, status, error_message)
            VALUES (%s, %s, now(), now(), 'failed', %s)
            """,
            (run_id, schedule_id, str(e)),
        )
        return {"status": "error", "error": str(e), "run_id": run_id}

    report_md = result.get("report", "")
    plan = result.get("plan", [])

    # 4. For alerts: evaluate if there's an issue
    alert_breached = False
    alert_eval = {}
    if schedule_type == "alert":
        threshold_context = ""
        alert_threshold = config.get("alert_threshold")
        alert_template = config.get("alert_template")
        if alert_threshold is not None:
            threshold_context = f"Alert template: {alert_template}, Threshold: {alert_threshold}"
        scope = config.get("alert_scope_json")
        if scope:
            if isinstance(scope, str):
                try:
                    scope = json.loads(scope)
                except Exception:
                    pass
            if isinstance(scope, dict):
                threshold_context += f", Scope: {json.dumps(scope)}"

        alert_eval = agent.evaluate_alert(report_md, question, threshold_context)
        alert_breached = alert_eval.get("breached", False)

        if not alert_breached:
            # No issue — log and exit without email
            execute_insert(
                """
                INSERT INTO bi_report_audit_log
                    (run_id, schedule_id, run_started_at, run_completed_at, status,
                     agent_plan_json, alert_breached)
                VALUES (%s, %s, now(), now(), 'no_breach', %s, FALSE)
                """,
                (run_id, schedule_id, json.dumps(plan)),
            )
            return {
                "status": "no_breach",
                "report": report_md,
                "alert_breached": False,
                "alert_summary": alert_eval.get("summary", ""),
                "run_id": run_id,
            }

    # 5. Generate HTML + PDF
    is_alert = schedule_type == "alert"
    title = f"{'ALERT: ' if is_alert else ''}{report_name}"

    # For alerts, prepend the alert summary to the report
    if is_alert and alert_eval:
        severity = alert_eval.get("severity", "medium").upper()
        summary = alert_eval.get("summary", "")
        report_md = f"**Alert Severity: {severity}**\n\n{summary}\n\n---\n\n{report_md}"

    html_report = markdown_to_html(report_md, title=title, is_alert=is_alert)
    pdf_bytes = html_to_pdf(html_report, report_md=report_md, title=title)

    # 6. Save PDF to UC Volume
    volume_path = None
    pdf_filename = make_pdf_filename(report_name)
    if pdf_bytes:
        volume_path = save_to_volume(
            pdf_bytes, report_name,
            workspace_client=workspace_client,
        )

    # 7. Send email
    date_str = datetime.utcnow().strftime("%Y-%m-%d")
    if is_alert:
        subject = f"[ALERT] {report_name} -- Threshold Breached {date_str}"
    else:
        subject = f"[Report] {report_name} -- {date_str}"

    email_sent = send_email(
        recipients=recipients,
        subject=subject,
        html_body=html_report,
        pdf_bytes=pdf_bytes,
        pdf_filename=pdf_filename,
    )

    # 8. Write audit log
    breach_value = alert_eval.get("key_metric_value") if alert_eval else None
    execute_insert(
        """
        INSERT INTO bi_report_audit_log
            (run_id, schedule_id, run_started_at, run_completed_at, status,
             agent_plan_json, alert_breached, alert_breach_value,
             report_volume_path, email_sent_to, email_sent_at)
        VALUES (%s, %s, now(), now(), %s, %s, %s, %s, %s, %s, %s)
        """,
        (
            run_id,
            schedule_id,
            "success",
            json.dumps(plan),
            alert_breached if is_alert else None,
            float(breach_value) if breach_value is not None else None,
            volume_path,
            recipients if email_sent else None,
            datetime.utcnow() if email_sent else None,
        ),
    )

    # 9. For alerts: update last_alert_sent_at
    if is_alert and alert_breached and email_sent:
        execute_insert(
            "UPDATE bi_report_schedules SET last_alert_sent_at = now() WHERE schedule_id = %s",
            (schedule_id,),
        )

    return {
        "status": "success",
        "report": report_md,
        "html": html_report,
        "pdf_bytes": pdf_bytes,
        "alert_breached": alert_breached,
        "alert_eval": alert_eval,
        "email_sent": email_sent,
        "volume_path": volume_path,
        "run_id": run_id,
    }


# ---------------------------------------------------------------------------
# Standalone preview (no schedule_id needed)
# ---------------------------------------------------------------------------
def generate_proactive_report(
    findings: list[dict],
    memory_update: dict,
    schedule_name: str = "Proactive Analysis",
) -> dict:
    """Generate HTML + PDF from proactive agent findings.

    Adapts the structured findings format from proactive_agent.py into the
    same report format used by run_schedule().

    Returns dict with: report_md, html, pdf_bytes, title.
    """
    # Build markdown report from findings
    parts = []
    parts.append(f"## Executive Summary\n")

    narrative = memory_update.get("narrative", "")
    if narrative:
        parts.append(narrative)
    parts.append("")

    if findings:
        parts.append(f"## Findings ({len(findings)} issues detected)\n")
        for i, f in enumerate(findings, 1):
            severity = f.get("severity", "notable").upper()
            sku = f.get("sku", "Unknown")
            ftype = f.get("type", "anomaly").replace("_", " ").title()
            desc = f.get("description", "")
            action = f.get("recommended_action", "")

            parts.append(f"### {i}. [{severity}] {ftype} — {sku}\n")
            if desc:
                parts.append(desc)
            if action:
                parts.append(f"\n**Recommended Action:** {action}")
            parts.append("")
    else:
        parts.append("## No Actionable Findings\n")
        parts.append("All monitored metrics are within normal ranges. No anomalies detected.")

    # Add watching list
    watching = memory_update.get("watching", [])
    if watching:
        parts.append("## Active Watch List\n")
        for w in watching:
            topic = w.get("topic", "")
            sev = w.get("severity", "")
            trend = w.get("trend", "")
            parts.append(f"- **{topic}** — {sev}, {trend}")
        parts.append("")

    # Add analysis details if present
    analysis = memory_update.get("analysis_text", "")
    if analysis and len(analysis) > 100:
        parts.append("## Detailed Analysis\n")
        # Strip the JSON memory update block from the analysis text
        import re
        cleaned = re.sub(r'```json\s*\{.*?\}\s*```', '', analysis, flags=re.DOTALL).strip()
        if cleaned:
            parts.append(cleaned)

    report_md = "\n".join(parts)
    title = f"Proactive Analysis — {schedule_name}"

    html_report = markdown_to_html(report_md, title=title)
    pdf_bytes = html_to_pdf(html_report, report_md=report_md, title=title)

    return {
        "report_md": report_md,
        "html": html_report,
        "pdf_bytes": pdf_bytes,
        "title": title,
    }


def run_proactive_schedule(schedule_id: str, workspace_client=None) -> dict:
    """Execute a proactive analysis schedule.

    Runs the proactive agent, generates the report, sends email, logs audit.
    """
    from proactive_agent import run_proactive_agent
    from db import execute_query, execute_insert

    # Read schedule config
    schedule_df = execute_query(
        """
        SELECT schedule_id, report_name, recipients, created_by, genie_space_ids
        FROM bi_report_schedules
        WHERE schedule_id = %s AND is_active = TRUE
        """,
        (schedule_id,),
    )
    if schedule_df.empty:
        return {"status": "error", "error": "Schedule not found or inactive"}

    config = schedule_df.iloc[0]
    report_name = config.get("report_name", "Proactive Analysis")
    recipients = config.get("recipients", [])
    created_by = config.get("created_by", "unknown@example.com")
    run_id = str(uuid.uuid4())

    if isinstance(recipients, str):
        recipients = [r.strip() for r in recipients.split(",") if r.strip()]
    if not recipients:
        recipients = [created_by]

    # Resolve genie spaces for this schedule
    from db import get_genies_by_ids, get_active_genies as _get_active_genies
    genie_space_ids = config.get("genie_space_ids")
    if genie_space_ids:
        genies_df = get_genies_by_ids(genie_space_ids)
    else:
        genies_df = _get_active_genies()
    genies = genies_df.to_dict("records")

    # Run proactive agent
    try:
        findings, memory_update = run_proactive_agent(
            schedule_id=schedule_id,
            run_id=run_id,
            workspace_client=workspace_client,
            genies=genies,
        )
    except Exception as e:
        logger.error("Proactive agent failed for schedule %s: %s", schedule_id, e)
        execute_insert(
            """
            INSERT INTO bi_report_audit_log
                (run_id, schedule_id, run_started_at, run_completed_at, status, error_message)
            VALUES (%s, %s, now(), now(), 'failed', %s)
            """,
            (run_id, schedule_id, str(e)),
        )
        return {"status": "error", "error": str(e), "run_id": run_id}

    # Generate report
    report = generate_proactive_report(findings, memory_update, schedule_name=report_name)

    # Save PDF
    volume_path = None
    if report.get("pdf_bytes"):
        volume_path = save_to_volume(
            report["pdf_bytes"], report_name,
            workspace_client=workspace_client,
        )

    # Send email
    date_str = datetime.utcnow().strftime("%Y-%m-%d")
    finding_count = len(findings)
    subject = f"[Proactive] {report_name} — {finding_count} findings — {date_str}"

    email_sent = send_email(
        recipients=recipients,
        subject=subject,
        html_body=report["html"],
        pdf_bytes=report.get("pdf_bytes"),
        pdf_filename=make_pdf_filename(report_name),
    )

    # Audit log
    execute_insert(
        """
        INSERT INTO bi_report_audit_log
            (run_id, schedule_id, run_started_at, run_completed_at, status,
             agent_plan_json, report_volume_path, email_sent_to, email_sent_at)
        VALUES (%s, %s, now(), now(), %s, %s, %s, %s, %s)
        """,
        (
            run_id,
            schedule_id,
            "success",
            json.dumps({"findings": len(findings), "watching": len(memory_update.get("watching", []))}),
            volume_path,
            recipients if email_sent else None,
            datetime.utcnow() if email_sent else None,
        ),
    )

    return {
        "status": "success",
        "findings": findings,
        "report_md": report["report_md"],
        "html": report["html"],
        "pdf_bytes": report.get("pdf_bytes"),
        "email_sent": email_sent,
        "volume_path": volume_path,
        "run_id": run_id,
        "execution_time": memory_update.get("execution_time", 0),
    }


def run_preview(question: str, user_email: str, workspace_client=None) -> dict:
    """Run the Supervisor Agent and generate HTML + PDF without saving a schedule.

    Returns dict with: report, html, pdf_bytes, plan, execution_time.
    """
    from supervisor import SupervisorAgent

    agent = SupervisorAgent(workspace_client=workspace_client)
    result = agent.run(question=question, user_email=user_email)
    report_md = result.get("report", "")

    html_report = markdown_to_html(report_md, title="Report Preview")
    pdf_bytes = html_to_pdf(html_report, report_md=report_md, title="Report Preview")

    return {
        "report": report_md,
        "html": html_report,
        "pdf_bytes": pdf_bytes,
        "plan": result.get("plan", []),
        "genie_calls": result.get("genie_calls", 0),
        "execution_time": result.get("execution_time", 0),
    }


# ---------------------------------------------------------------------------
# CLI entrypoint (for Databricks Job tasks)
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    import sys
    logging.basicConfig(level=logging.INFO)

    if len(sys.argv) < 2:
        print("Usage: python report_runner.py <schedule_id>")
        sys.exit(1)

    schedule_id = sys.argv[1]
    result = run_schedule(schedule_id)
    print(json.dumps({k: v for k, v in result.items() if k not in ("pdf_bytes", "html")}, indent=2, default=str))
