import type { GraphResponse, TableNodeData } from '../types'
import { mapColumnType, type Dialect } from './typeMapping'

export interface UnsupportedTypeEntry {
  table: string // fully-qualified catalog.schema.table
  column: string
  originalType: string
  mappedTo: string
}

export interface DdlResult {
  sql: string
  unsupported: UnsupportedTypeEntry[]
}

function quoteIdent(dialect: Dialect, ident: string): string {
  return dialect === 'sqlserver' ? `[${ident}]` : `"${ident}"`
}

/** Flattened into a single DDL "schema" identifier -- ER/Studio (like any relational
 * tool) has no concept of a 3-level catalog.schema.table namespace, and two different
 * catalogs can legitimately have same-named schemas (e.g. two catalogs both having an
 * "erp" schema) -- collapsing catalog+schema into one identifier keeps every generated
 * table name unique regardless of how many catalogs are in scope. */
function ddlSchemaName(catalog: string, schema: string): string {
  return `${catalog}__${schema}`
}

function qualifiedTable(dialect: Dialect, catalog: string, schema: string, table: string): string {
  return `${quoteIdent(dialect, ddlSchemaName(catalog, schema))}.${quoteIdent(dialect, table)}`
}

/**
 * Physical model DDL for `graph` (already scoped by the caller via scopeGraph(), same as
 * the Markdown/YAML/JSON exports). Declared foreign keys (graph.edges where
 * inferred === false) become real FOREIGN KEY constraints -- inferred/undeclared
 * relationships (server/graph.py's infer_relationships heuristic) NEVER do, since they
 * are a guess, not a real constraint; they're surfaced in metadata.csv instead (see
 * metadataCsv.ts). This split is covered by ddlBuilder tests -- do not weaken it.
 */
export function buildDdl(graph: GraphResponse, dialect: Dialect): DdlResult {
  const nodes = graph.nodes as TableNodeData[]
  const unsupported: UnsupportedTypeEntry[] = []
  const lines: string[] = []

  lines.push(`-- Physical model generated by Catalog ERD Explorer (dialect: ${dialect}).`)
  lines.push(`-- Scope: ${graph.unscoped ? 'all catalogs visible to this deployment' : graph.catalogs.join(', ')}.`)
  lines.push('')

  for (const node of nodes) {
    const qualified = qualifiedTable(dialect, node.catalog, node.schema, node.table)
    lines.push(`-- Source: ${node.catalog}.${node.schema}.${node.table}${node.comment ? ` -- ${node.comment}` : ''}`)
    lines.push(`CREATE TABLE ${qualified} (`)

    // Comment and definition are built as separate entries, joined below with the comma
    // placed only between DEFINITIONS -- putting a trailing "-- comment" on the same
    // line as a column def would swallow the following comma into the line comment
    // (everything after `--` runs to end of line), silently breaking the statement for
    // any parser, so each comment gets its own line directly above its column instead.
    const defs: Array<{ comment?: string; def: string }> = []
    const pkCols: string[] = []
    for (const col of node.columns) {
      const mapping = mapColumnType(col.type, dialect)
      if (mapping.unsupported && mapping.originalType) {
        unsupported.push({
          table: `${node.catalog}.${node.schema}.${node.table}`,
          column: col.name,
          originalType: mapping.originalType,
          mappedTo: mapping.sqlType,
        })
      }
      const notNull = col.is_pk ? ' NOT NULL' : ''
      const comment = mapping.unsupported
        ? `-- originally ${mapping.originalType} (no direct ${dialect} equivalent)`
        : col.comment
          ? `-- ${col.comment.replace(/\s+/g, ' ')}`
          : undefined
      defs.push({ comment, def: `${quoteIdent(dialect, col.name)} ${mapping.sqlType}${notNull}` })
      if (col.is_pk) pkCols.push(quoteIdent(dialect, col.name))
    }
    if (pkCols.length > 0) {
      defs.push({ def: `CONSTRAINT ${quoteIdent(dialect, `${node.table}_pk`)} PRIMARY KEY (${pkCols.join(', ')})` })
    }
    const body = defs
      .map(({ comment, def }, i) => {
        const commentLine = comment ? `  ${comment}\n` : ''
        const separator = i < defs.length - 1 ? ',' : ''
        return `${commentLine}  ${def}${separator}`
      })
      .join('\n')
    lines.push(body)
    lines.push(');')
    lines.push('')
  }

  const nodeById = new Map(nodes.map((n) => [n.id, n]))
  const declaredEdges = graph.edges.filter((e) => !e.inferred)
  if (declaredEdges.length > 0) {
    lines.push(
      '-- Foreign keys (declared Unity Catalog constraints only -- undeclared/inferred',
      '-- relationships are listed in metadata.csv, never as a DDL constraint here).',
    )
    for (const edge of declaredEdges) {
      const source = nodeById.get(edge.source)
      const target = nodeById.get(edge.target)
      if (!source || !target) continue // endpoint outside the current export scope
      const sourceQualified = qualifiedTable(dialect, source.catalog, source.schema, source.table)
      const targetQualified = qualifiedTable(dialect, target.catalog, target.schema, target.table)
      const fkName = quoteIdent(dialect, edge.constraint_name ?? `${source.table}_${target.table}_fk`)
      const fkCols = edge.fk_columns.map((c) => quoteIdent(dialect, c)).join(', ')
      const pkCols = edge.pk_columns.map((c) => quoteIdent(dialect, c)).join(', ')
      lines.push(
        `ALTER TABLE ${sourceQualified} ADD CONSTRAINT ${fkName} FOREIGN KEY (${fkCols}) REFERENCES ${targetQualified} (${pkCols});`,
      )
    }
    lines.push('')
  }

  return { sql: lines.join('\n'), unsupported }
}
