import { useEffect, useState } from "react";
import { Sparkles, X } from "lucide-react";
import { api, type Explanation } from "../api";
import { useToast } from "./Toast";
import { Markdown } from "./Markdown";
import { Spinner, Chip } from "./ui";

// Triage Copilot drawer: given a finding id, calls the Foundation Model explain
// endpoint and renders the markdown diagnosis + remediations.
export function CopilotModal({
  findingId,
  context,
  onClose,
}: {
  findingId: number | null;
  context?: string; // e.g. object name / external id shown as a subtitle
  onClose: () => void;
}) {
  const toast = useToast();
  const [data, setData] = useState<Explanation | null>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (findingId == null) {
      setData(null);
      return;
    }
    let cancelled = false;
    setLoading(true);
    setData(null);
    api
      .explainFinding(findingId)
      .then((res) => {
        if (!cancelled) setData(res);
      })
      .catch((e) => {
        if (!cancelled) {
          toast({ kind: "error", title: "Copilot unavailable", detail: e instanceof Error ? e.message : String(e) });
          onClose();
        }
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [findingId]);

  // close on Escape
  useEffect(() => {
    if (findingId == null) return;
    const onKey = (e: KeyboardEvent) => e.key === "Escape" && onClose();
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [findingId, onClose]);

  if (findingId == null) return null;

  return (
    <div className="fixed inset-0 z-50 flex justify-end" role="dialog" aria-modal="true" aria-label="Triage Copilot">
      <div className="absolute inset-0 bg-black/50 backdrop-blur-[2px]" onClick={onClose} />
      <div
        className="relative flex h-full w-full max-w-[560px] flex-col border-l border-line bg-surface shadow-pop"
        style={{ animation: "wt-toast-in 0.2s ease-out" }}
      >
        <div className="flex items-start justify-between gap-3 border-b border-line px-5 py-4">
          <div className="flex items-center gap-3">
            <span
              className="flex h-9 w-9 items-center justify-center rounded-[10px]"
              style={{ background: "linear-gradient(135deg,#FF5F46,#FF3621)" }}
            >
              <Sparkles size={18} className="text-white" />
            </span>
            <div>
              <div className="text-[15px] font-semibold text-text-primary">Triage Copilot</div>
              <div className="text-[12px] text-text-secondary">
                {loading ? "Analyzing finding…" : data ? <>via {data.model}</> : context ?? ""}
              </div>
            </div>
          </div>
          <button
            onClick={onClose}
            className="rounded-md p-1.5 text-text-secondary transition-colors hover:bg-hover hover:text-text-primary"
            aria-label="Close"
          >
            <X size={18} />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto px-5 py-4">
          {context && (
            <div className="mb-3">
              <Chip>finding #{findingId}</Chip> <span className="text-[12px] text-text-secondary">{context}</span>
            </div>
          )}
          {loading && (
            <div className="flex items-center gap-3 py-10 text-[13px] text-text-secondary">
              <Spinner size={18} />
              Consulting the Foundation Model…
            </div>
          )}
          {data && <Markdown text={data.explanation} />}
        </div>

        {data && (
          <div className="border-t border-line px-5 py-3 text-[11px] text-text-disabled">
            Generated by {data.model} · grounded in this finding's facts
          </div>
        )}
      </div>
    </div>
  );
}
